---
# file: roles/docker/tasks/docker.yml

- name: add apt key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg

- name: add docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: install docker
  apt:
    name: docker-ce=18.06.1~ce~3-0~ubuntu
    force: yes
    update_cache: yes
    cache_valid_time: 600

- name: enable docker service
  systemd:
    name: docker
    enabled: yes
  notify: "restart docker"
