---
# file: roles/swarm/tasks/main.yml

- name: check swarm mode status
  tags: swarm
  command: 'docker info'
  register: 'docker_info'
  changed_when: false
  check_mode: no

- name: initialize swarm on manager-0
  tags: swarm
  command: 'docker swarm init --advertise-addr 192.168.20.120'
  when: >
    'Swarm: inactive' in docker_info.stdout and
    inventory_hostname == 'manager-0'

- name: capture join token
  tags: swarm
  command: 'docker swarm join-token -q manager'
  changed_when: false
  register: 'docker_swarm_manager_token'
  when: >
    inventory_hostname == 'manager-0'

- name: copy swarm token from manager-0 to current worker
  tags: swarm
  set_fact:
    docker_swarm_manager_token: "{{ hostvars['manager-0']['docker_swarm_manager_token'] }}"
  changed_when: false
  when: >
        inventory_hostname != 'manager-0'

- name: joining workers to cluster as manager
  tags: swarm
  command: >
    docker swarm join
    --token {{ docker_swarm_manager_token.stdout }}
    192.168.20.120
  when: >
    inventory_hostname != 'manager-0' and
    'Swarm: active' not in docker_info.stdout and
    'Swarm: pending' not in docker_info.stdout
